"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os

from config.env import env, BASE_DIR
from config.settings.logging import DICT_LOG, configure_logging

env.read_env(BASE_DIR(".env"))


DEBUG = env.bool("DJANGO_DEBUG", default=True)

# Site settings
APP_NAME = "leasify"

FRONTEND_DOMAIN = env.str("FRONTEND_DOMAIN", "localhost")
FRONTEND_URL = env.str("FRONTEND_URL", "http://localhost:5173")
COMPANY_NAME = "Bisika Apartments Ltd."
COMPANY_ADDRESS = "Embu, Kenya"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECURITY_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


LOCAL_APPS = [
    "users",
    "payments",
    "apartments",
    "tenancy",
    "billing",
]

THIRD_PARTY_APPS = [
    "drf_standardized_errors",
    "django_extensions",
    "django_structlog",
    "rest_framework",
    "corsheaders",
]


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    *LOCAL_APPS,
    *THIRD_PARTY_APPS,
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django_structlog.middlewares.RequestMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.settings.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR("templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
## CSRF
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = False
CSRF_TRUSTED_ORIGINS = [FRONTEND_URL]
CSRF_COOKIE_SECURE = False


## SESSIONS
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_HTTPONLY = True
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
SESSION_COOKIE_SECURE = True

## CORS
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [FRONTEND_URL, "http://localhost:8000", "http://127.0.0.1:8000"]


## Rest
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ("config.settings.auth.SessionAuthentication",),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "EXCEPTION_HANDLER": "drf_standardized_errors.handler.exception_handler",
    "DEFAULT_THROTTLE_RATES": {
        "anon_sustained": "50/day",
        "user_sustained": "100/day",
        "failed_login_attempts": "5/hour",
        "password_changes": "3/day",
        "password_resets": "3/day",
        "email_verifications": "3/day",
    },
}

WSGI_APPLICATION = "config.wsgi.application"

## Logging
LOGGING = DICT_LOG
configure_logging()

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR("db.sqlite3"),
    }
}

## Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", "OPTIONS": {"min_length": 6}},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

## Caching
CACHES = {
    "default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache", "LOCATION": "memory://"},
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Africa/Nairobi"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR("static")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


## User model
AUTH_USER_MODEL = "users.User"

## CELERY
CELERY_BROKER_URL = CACHES["default"]["LOCATION"]
CELERY_TASK_ALWAYS_EAGER = False
CELERY_IGNORE_RESULT = True
CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = "UTC"


# MPESA
MPESA_CONFIG = {
    "AUTHENTICATE_URL": os.environ["MPESA_AUTHENTICATE_URL"],
    "CONSUMER_KEY": os.environ["MPESA_CONSUMER_KEY"],
    "CONSUMER_SECRET": os.environ["MPESA_CONSUMER_SECRET"],
    "SHORTCODE": os.environ["MPESA_SHORTCODE"],
    "PASSKEY": os.environ["MPESA_PASSKEY"],
    "CALLBACK_URL": os.environ["MPESA_CALLBACK_URL"],
    "QUERY_URL": os.environ["MPESA_EXPRESS_URL_QUERY"],
    "INITIATE_URL": os.environ["MPESA_EXPRESS_URL_INITIATE"],
}

FLOWER_URL = "http://localhost:5555"
FLOWER_URL_PREFIX = "flower"


from config.settings.emails import *
