"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from config.env import env, BASE_DIR, APP_DIRS
from config.settings.logging import DICT_LOG, configure_logging

env.read_env(BASE_DIR(".env"))


DEBUG = env.bool("DJANGO_DEBUG", default=True)

# Site settings
APP_NAME = "leasify"
COMPANY_NAME = "Bisika Apartments Ltd."
COMPANY_ADDRESS = "Embu, Kenya"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/



LOCAL_APPS = [
    "leasify.users.apps.UsersConfig",
    "leasify.billing.apps.BillingConfig",
    "leasify.tenancy.apps.TenancyConfig",
    "leasify.payments.apps.PaymentsConfig",
    "leasify.apartments.apps.ApartmentsConfig",
]

THIRD_PARTY_APPS = [
    "drf_standardized_errors",
    "django_extensions",
    "django_structlog",
    "rest_framework",
    "corsheaders",
    "django_celery_results"
]


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    *LOCAL_APPS,
    *THIRD_PARTY_APPS,
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django_structlog.middlewares.RequestMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.settings.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR("leasify/templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

## Rest
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ("config.settings.auth.SessionAuthentication",),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "EXCEPTION_HANDLER": "drf_standardized_errors.handler.exception_handler",
    "DEFAULT_THROTTLE_RATES": {
        "anon_sustained": "50/day",
        "user_sustained": "100/day",
        "failed_login_attempts": "5/hour",
        "password_changes": "3/day",
        "password_resets": "3/day",
        "email_verifications": "3/day",
    },
}

WSGI_APPLICATION = "config.wsgi.application"

## Logging
LOGGING = DICT_LOG
configure_logging()

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR("db.sqlite3")
    }
}

## Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", "OPTIONS": {"min_length": 6}},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

## Caching
CACHES = {
    "default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache", "LOCATION": "memory://"},
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Africa/Nairobi"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR("static")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

## User model
AUTH_USER_MODEL = "users.User"

## CELERY
CELERY_BROKER_URL = "memory://"
CELERY_TASK_ALWAYS_EAGER = True
CELERY_IGNORE_RESULT = False
CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = "UTC"

# DRF_STANDARDIZED_ERRORS
DRF_STANDARDIZED_ERRORS = {"ENABLE_IN_DEBUG_FOR_UNHANDLED_EXCEPTIONS": True}

# EMAILS
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = env.str("EMAIL_HOST")
EMAIL_PORT = env.int("EMAIL_PORT")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS")
EMAIL_HOST_USER = env.str("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD")

ADMINS = [tuple(admin.split(":", 1)) for admin in env.list("ADMINS")]

from config.settings.mpesa import *
from config.settings.security import *

# We import security first to obtain FRONTEND_DOMAIN
SERVER_EMAIL = f"server@{FRONTEND_DOMAIN}"
DEFAULT_FROM_EMAIL = f"noreply@{FRONTEND_DOMAIN}"