# Generated by Django 5.2.6 on 2026-05-20 13:32

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ref_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('debit', 'Incoming Payments'), ('credit', 'Outgoing Payments')], max_length=10)),
                ('phone_number', common.fields.PhoneNumberModelField(error_messages={'invalid': 'Phone number must be in the format +254XXXXXXXXX'}, max_length=13, validators=[common.fields.PhoneNumberValidator()])),
                ('payee', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
