# Generated by Django 5.2.6 on 2026-05-21 15:01

import common.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('initiator', models.CharField(choices=[('SGT', 'System initiated'), ('TPY', 'System initiated'), ('APY', 'System initiated')])),
                ('phone_number', common.fields.PhoneNumberModelField(editable=False, error_messages={'invalid': 'Phone number must be in the format +254XXXXXXXXX'}, max_length=13, validators=[common.fields.PhoneNumberValidator()])),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('debit', 'Incoming Payments'), ('credit', 'Outgoing Payments')], editable=False, max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Payment has been initiated but not confirmed'), ('confirmed', 'Payment has been confirmed'), ('failed', 'Payment could not be completed')], default='pending')),
                ('payee', models.CharField(blank=True, max_length=30, null=True)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.billingperiod')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx')],
            },
        ),
    ]
