# Generated by Django 5.2.6 on 2026-03-06 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tenancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenancy.tenancy'),
        ),
    ]
