# Generated by Django 5.2.6 on 2026-07-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='unpaid')),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ('-start_date', '-created_at'),
                'permissions': [('complete_billingperiod', 'Can manually set the billing period to PAID')],
            },
        ),
    ]
