# Generated by Django 5.2.6 on 2026-05-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rent_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
    ]
