# Generated by Django 5.2.6 on 2026-05-22 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingperiod',
            name='tenancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billings', to='tenancy.tenancy'),
        ),
        migrations.AddIndex(
            model_name='billingperiod',
            index=models.Index(fields=['tenancy', 'start_date', 'end_date'], name='billing_bil_tenancy_a4929d_idx'),
        ),
    ]
