# Generated by Django 5.2.6 on 2026-02-09 08:28

import mixins.model_full_clean
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('NEW', 'New Block'), ('OLD', 'OLD Block')], max_length=10)),
                ('unit_number', models.PositiveSmallIntegerField()),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rentable', models.BooleanField(default=True, help_text='Viewable and available to rent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('block', 'unit_number')},
            },
            bases=(mixins.model_full_clean.ModelExceptionMixin, models.Model),
        ),
    ]
