# Generated by Django 5.2.6 on 2026-05-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.CharField(choices=[('NEW', 'New Block'), ('OLD', 'Old Block')], max_length=10)),
                ('unit_number', models.PositiveSmallIntegerField()),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rentable', models.BooleanField(default=True, help_text='Viewable and available to rent')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': (('view_overview', 'Can view the apartments overview status for the semester'),),
                'unique_together': {('block', 'unit_number')},
            },
        ),
    ]
