# Generated by Django 5.2.6 on 2025-12-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('NEW', 'New Block'), ('OLD', 'OLD Block')], max_length=10)),
                ('unit_number', models.PositiveSmallIntegerField()),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rentable', models.BooleanField(default=True, help_text='True = apartment is rentable currently')),
            ],
            options={
                'unique_together': {('block', 'unit_number')},
            },
        ),
    ]
