# Generated by Django 5.2.6 on 2026-05-29 06:41

import django.db.models.deletion
import tenancy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Tenant has paid and the tenancy is active'), ('reserved', 'Tenant has made a reservation but has not paid yet'), ('defaulting', 'Active tenant has not yet paid'), ('terminated', 'Tenancy has been expired')], default='reserved', max_length=20)),
                ('date_joined', models.DateField()),
                ('reservation_expiry', models.DateField(default=tenancy.models.default_expiry)),
                ('termination_reason', models.CharField(blank=True, choices=[('managerial', 'Managerial decision to terminate'), ('expired', 'Reservation expired'), ('voluntary', 'Voluntary termination'), ('non_payment', 'Tenant failed to pay')], null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apartments.apartment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
