# Generated by Django 5.2.6 on 2026-05-20 13:32

import django.db.models.deletion
import tenancy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Tenant has made a reservation but has not paid yet'), ('active', 'Tenant has paid and the tenancy is active'), ('terminated', 'Tenancy has been explicitly terminated')], default='pending', max_length=20)),
                ('reservation_expriry', models.DateField(default=tenancy.models.default_expiry)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apartments.apartment')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': (('tenancy_extend_lease', 'Allow tenancy lease time to be extended'), ('tenancy_extend_reservation_expiration', 'Allow pending tenants to extend their stay')),
            },
        ),
    ]
