# Generated by Django 5.2.6 on 2026-08-01 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['checkout_id'], name='payments_pa_checkou_c30a92_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['receipt_no'], name='payments_pa_receipt_c53ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['idempotency_key'], name='payments_pa_idempot_d55485_idx'),
        ),
    ]
