# Generated by Django 5.2.6 on 2026-08-07 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'reserved', 'defaulting'])), fields=('apartment',), name='unique_active_pending_per_apartment', violation_error_message='Apartment already associated with a tenant'),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'reserved', 'defaulting'])), fields=('user',), name='unique_active_pending_per_user', violation_error_message='User already has a tenancy'),
        ),
    ]
